[project]
name = "work-framework"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.membership-registry]
path = "contracts/identity-manager.clar"
depends_on = []

[contracts.proposal-manager]
path = "contracts/governance-manager.clar"
depends_on = []

[contracts.treasury-controller]
path = "contracts/financial-controller.clar"
depends_on = []

[contracts.voting-engine]
path = "contracts/decision-engine.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
